//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.15 at 03:49:47 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xml.netbeans.org/schema/books", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.netbeans.xml.schema.books;
